"use strict";

const $ = (s, c = document) => c.querySelector(s);
const $$ = (s, c = document) => [...c.querySelectorAll(s)];
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

const data = {
  employees: [
    { id: "EMP-021", name: "Jordan Lee", role: "Retail Employee", outlet: "North Point", status: "Active" },
    { id: "EMP-034", name: "Avery Singh", role: "Technical Staff", outlet: "Central Hub", status: "Active" },
    { id: "EMP-047", name: "Nora Patel", role: "Accounts", outlet: "Head Office", status: "Active" },
    { id: "EMP-052", name: "Sam Rivera", role: "Retail Employee", outlet: "West Market", status: "On leave" }
  ],
  vendors: [
    { id: "VND-08", name: "Orbit Networks", contact: "Mina Ford", category: "Routers", status: "Approved" },
    { id: "VND-14", name: "Copperline Co.", contact: "Eli Brooks", category: "Cabling", status: "Approved" },
    { id: "VND-19", name: "Signal Supply", contact: "Hana Kim", category: "Modems", status: "Review" }
  ],
  plans: [
    { type: "Broadband", plan: "Unlimited 64 Kbps", billing: "Monthly", charge: 225 },
    { type: "Dial-Up", plan: "Essential 56 Kbps", billing: "Hourly", charge: 1.5 },
    { type: "Landline", plan: "Business Standard", billing: "Monthly", charge: 84.2 }
  ],
  orders: [
    { id: "D0000000001", account: "4851029384756102", customer: "Maya Chen", type: "Broadband", plan: "Unlimited 64 Kbps", status: "Awaiting feasibility", due: 269.38 },
    { id: "D0000000002", account: "6284102938475610", customer: "Theo Brooks", type: "Landline", plan: "Business Standard", status: "Feasible", due: 84.2 },
    { id: "D0000000003", account: "9182736450129384", customer: "Priya Nair", type: "Dial-Up", plan: "Essential 56 Kbps", status: "Not Feasible", due: 0 },
    { id: "D0000000004", account: "1029384756102938", customer: "Jordan Ellis", type: "Broadband", plan: "Unlimited 64 Kbps", status: "Connection Provided", due: 225 }
  ],
  equipment: [
    { serial: "RTR-NX-88210", type: "Router", account: "4851029384756102", assigned: "2026-09-02" },
    { serial: "MDM-NX-41002", type: "Modem", account: "1029384756102938", assigned: "2026-09-01" }
  ],
  connectionStatus: { "4851029384756102": "Active", "6284102938475610": "Temporarily Inactive", "9182736450129384": "Permanently Inactive", "1029384756102938": "Active" },
  customer: {
    name: "Maya Chen",
    account: "4851029384756102",
    email: "maya.chen@example.com",
    phone: "+1 555 014 8720",
    address: "14 Mercer Avenue, North Point",
    contact: "Email",
    memberSince: "March 2025"
  },
  customerBills: [
    { id: "NXB-092026", period: "September 2026", total: 252.54, due: "Oct 03, 2026", status: "Payment due" },
    { id: "NXB-082026", period: "August 2026", total: 225, due: "Sep 03, 2026", status: "Paid" },
    { id: "NXB-072026", period: "July 2026", total: 225, due: "Aug 03, 2026", status: "Paid" }
  ]
};

const roles = {
  customer: { name: "Customer", code: "CUS", context: "My Nexus account", nav: [["overview", "Home"], ["customer-new-service", "New Service"], ["customer-orders", "My Orders"], ["customer-connection", "My Connection"], ["customer-billing", "Bills & Payments"], ["customer-profile", "Profile"], ["customer-support", "Support"]] },
  admin: { name: "Admin / Manager", code: "ADM", context: "Network administration", nav: [["overview", "Overview"], ["employees", "Employee Management"], ["inventory", "Stock / Inventory"], ["vendors", "Vendor Management"], ["shops", "Retail Shops"], ["plans", "Plan Management"]] },
  retail: { name: "Retail Outlet Employee", code: "RTL", context: "North Point retail outlet", nav: [["overview", "Outlet Overview"], ["new-order", "New Order"], ["tracking", "Order Tracking"], ["connections", "Connection Details"], ["payments", "Payment Records"]] },
  technical: { name: "Technical Staff", code: "TEC", context: "Field service operations", nav: [["overview", "Technical Overview"], ["queue", "Order Feasibility Queue"], ["connection-manager", "Connection Manager"], ["equipment", "Equipment / Product Details"]] },
  accounts: { name: "Accounts Department", code: "ACC", context: "Revenue operations", nav: [["overview", "Finance Overview"], ["billing", "Bill Generation"], ["payment-updates", "Payment Updates"], ["charge-settings", "Charge Settings"]] }
};

let activeRole = "admin", currentView = "overview", modalState = null, lastBillTotal = 0, toastTimer;
const icons = { overview: "⌁", employees: "♙", inventory: "▦", vendors: "◇", shops: "⌂", plans: "≡", "new-order": "+", tracking: "◎", connections: "↔", payments: "$", queue: "≣", "connection-manager": "⌁", equipment: "▣", billing: "$", "payment-updates": "✓", "charge-settings": "⚙" };

Object.assign(icons, { "customer-new-service": "+", "customer-orders": "O", "customer-connection": "C", "customer-billing": "$", "customer-profile": "P", "customer-support": "?" });

function showToast(message) { const el = $("#toast"); el.textContent = message; el.classList.add("is-visible"); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove("is-visible"), 2800); }
function chip(status) { const kind = /active|approved|feasible|provided|paid|healthy|published|assigned|open/i.test(status) && !/inactive|not feasible/i.test(status) ? "positive" : /leave|review|awaiting|temporary|pending|low/i.test(status) ? "warning" : "danger"; return `<span class="status-chip status-chip--${kind}">${status}</span>`; }
function heading(kicker, title, copy, action = "") { return `<header class="page-heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${copy}</p></div>${action}</header>`; }
function metric(label, value, note, tone = "") { return `<article class="metric ${tone}"><p>${label}</p><strong>${value}</strong><span>${note}</span></article>`; }
function table(head, rows) { return `<div class="table-scroll"><table><thead><tr>${head.map(h => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`; }
function section(kicker, title) { return `<div class="section-heading"><div><p class="eyebrow">${kicker}</p><h3>${title}</h3></div></div>`; }
function activity() { return `<div class="dashboard-grid"><section class="surface feed-panel">${section("Live administration", "Today’s activity")}<div class="feed"><p><i></i><strong>North Point roster approved</strong><small>Weekend shift coverage confirmed · 09:42</small></p><p><i class="teal"></i><strong>Orbit Networks delivery received</strong><small>40 routers added at Central Hub · 08:26</small></p><p><i class="amber"></i><strong>Reorder threshold reached</strong><small>Copper Cable · 100m needs review · 07:58</small></p></div></section><aside class="surface signal-panel"><p class="eyebrow">Outlet availability</p><strong>16<span>/18</span></strong><p>shops reporting normally</p><div class="signal-bars"><i></i><i></i><i></i><i></i><i></i></div></aside></div>`; }

function employeeTable(items = data.employees) { return table(["Employee", "Role", "Assignment", "Status", "Actions"], items.map(e => `<tr><td><b>${e.name}</b><small>${e.id}</small></td><td>${e.role}</td><td>${e.outlet}</td><td>${chip(e.status)}</td><td class="row-actions"><button data-edit-employee="${e.id}">Edit</button><button class="danger-link" data-delete-employee="${e.id}">Delete</button></td></tr>`)); }
function vendorTable() { return table(["Vendor", "Contact", "Category", "Status", "Actions"], data.vendors.map(v => `<tr><td><b>${v.name}</b><small>${v.id}</small></td><td>${v.contact}</td><td>${v.category}</td><td>${chip(v.status)}</td><td class="row-actions"><button data-edit-vendor="${v.id}">Edit</button><button class="danger-link" data-delete-vendor="${v.id}">Delete</button></td></tr>`)); }
function planTable() { return table(["Connection", "Plan", "Billing basis", "Charge", "Status"], data.plans.map(p => `<tr><td><span class="service-code">${p.type.slice(0, 2).toUpperCase()}</span>${p.type}</td><td><b>${p.plan}</b></td><td>${p.billing}</td><td class="number-cell">${money.format(p.charge)}${p.billing === "Hourly" ? "/hr" : "/mo"}</td><td>${chip("Published")}</td></tr>`)); }

function adminView(view) {
  if (view === "overview") return `${heading("Management pulse", "Good morning, Admin.", "A concise view of the people, outlets, and stock keeping Nexus moving.", `<button class="button button--primary" data-view-link="employees">Manage employees →</button>`)}<div class="metric-grid">${metric("Retail shops", "18", "16 open today", "metric--signal")}${metric("Active employees", "142", "8 teams on duty")}${metric("Low-stock items", "07", "2 require action")}${metric("Approved vendors", "12", "3 deliveries inbound")}</div>${activity()}`;
  if (view === "employees") return `${heading("People operations", "Employee management", "Maintain staff access, assignments, and employment status.", `<button class="button button--primary" data-add="employee">+ Add employee</button>`)}<section class="surface table-panel"><div class="section-heading"><div><p class="eyebrow">Team directory</p><h3>${data.employees.length} employee records</h3></div><input class="compact-search" id="employeeSearch" type="search" placeholder="Search employees" /></div><div id="employeeTable">${employeeTable()}</div></section>`;
  if (view === "inventory") return `${heading("Stock control", "Inventory at a glance", "Track customer-premise equipment across retail outlets and hubs.")}<div class="metric-grid">${metric("Wi-Fi routers", "384", "41 allocated this week", "metric--signal")}${metric("DSL modems", "217", "Stock healthy")}${metric("Cable reels", "63", "7 below reorder point")}${metric("Handsets", "126", "18 in transit")}</div><section class="surface table-panel">${section("Warehouse ledger", "Current stock")}${table(["Product", "SKU", "On hand", "Reserved", "Reorder at", "Health"], [["Nexus Wi-Fi 6 Router", "RTR-W6-20", "184", "31", "60", chip("Healthy")], ["DSL Bridge Modem", "MDM-D4-11", "72", "18", "50", chip("Low stock")], ["Copper Cable · 100m", "CBL-CU-10", "63", "24", "70", chip("Reorder")], ["Desk Handset", "PHN-L2-08", "126", "12", "40", chip("Healthy")]].map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`))}</section>`;
  if (view === "vendors") return `${heading("Supply partners", "Vendor management", "Keep procurement contacts and approval states current.", `<button class="button button--primary" data-add="vendor">+ Add vendor</button>`)}<section class="surface table-panel">${section("Vendor directory", `${data.vendors.length} active records`)}<div id="vendorTable">${vendorTable()}</div></section>`;
  if (view === "shops") return `${heading("Retail network", "Retail shops", "Monitor opening status, staff coverage, and today’s order flow.")}<div class="shop-grid">${[["North Point", "Open", "12 staff", "38 orders"], ["West Market", "Open", "9 staff", "24 orders"], ["Civic Centre", "Open", "15 staff", "42 orders"], ["Lake Road", "Opening 10:00", "7 staff", "18 orders"]].map((s, i) => `<article class="surface shop-card"><span>0${i + 1}</span><div><small>Retail outlet</small><h3>${s[0]}</h3></div>${chip(s[1])}<dl><div><dt>Coverage</dt><dd>${s[2]}</dd></div><div><dt>Today</dt><dd>${s[3]}</dd></div></dl></article>`).join("")}</div>`;
  return `${heading("Commercial catalogue", "Plan management", "Review current connection products and customer-facing charges.", `<button class="button button--primary" id="addPlan">+ Add plan</button>`)}<section class="surface table-panel">${section("Current plans", "3 published")}<div id="planTable">${planTable()}</div></section>`;
}

function orderResult(o) { return `<article class="result-card"><div class="result-card__top"><div><small>Order ID</small><strong>${o.id}</strong></div>${chip(o.status)}</div><div class="detail-grid"><div><small>Customer</small><strong>${o.customer}</strong></div><div><small>Connection</small><strong>${o.type}</strong></div><div><small>Selected plan</small><strong>${o.plan}</strong></div><div><small>Account ID</small><strong class="mono">${o.account}</strong></div></div><ol class="progress-track"><li class="is-done">Order captured</li><li class="${o.status !== "Awaiting feasibility" ? "is-done" : "is-current"}">Feasibility check</li><li class="${o.status === "Connection Provided" ? "is-done" : ""}">Connection provided</li></ol></article>`; }
function accountResult(o, payments = false) { return `<article class="result-card"><div class="result-card__top"><div><small>Account holder</small><strong>${o.customer}</strong></div>${chip(data.connectionStatus[o.account])}</div><div class="detail-grid"><div><small>Account ID</small><strong class="mono">${o.account}</strong></div><div><small>Connection</small><strong>${o.type}</strong></div><div><small>Plan</small><strong>${o.plan}</strong></div><div><small>${payments ? "Current due" : "Service address"}</small><strong>${payments ? money.format(o.due) : "14 Mercer Avenue"}</strong></div></div>${payments ? `<div class="payment-strip"><div><small>Last payment</small><strong>$225.00</strong><span>Aug 30, 2026</span></div><div><small>Amount due</small><strong>${money.format(o.due)}</strong><span>Due Sep 30, 2026</span></div><div><small>Payment status</small>${chip(o.due ? "Payment due" : "Paid")}</div></div>` : ""}</article>`; }

function retailView(view) {
  if (view === "overview") return `${heading("North Point · Outlet 04", "Ready for the next customer.", "Fast paths for order entry, tracking, and account enquiries.", `<button class="button button--primary" data-view-link="new-order">Place new order →</button>`)}<div class="metric-grid">${metric("Orders today", "38", "11 awaiting feasibility", "metric--signal")}${metric("Connections live", "29", "76% completion rate")}${metric("Payments posted", "$6,420", "Across 31 accounts")}${metric("Average service", "06:14", "2 min faster than target")}</div><section class="quick-grid"><button data-view-link="new-order"><span>+</span><strong>New order</strong><small>Register a customer connection</small></button><button data-view-link="tracking"><span>◎</span><strong>Track order</strong><small>Find progress by Order ID</small></button><button data-view-link="payments"><span>$</span><strong>Payment lookup</strong><small>Review an account balance</small></button></section>`;
  if (view === "new-order") return `${heading("Customer acquisition", "Place a new order", "Capture the essentials in one pass. Required fields are marked with an asterisk.")}<form class="surface form-panel" id="orderForm"><div class="form-section"><span>01</span><div><h3>Personal details</h3><p>Information used to create the customer account.</p></div></div><div class="form-grid"><div class="field"><label for="customerName">Full name *</label><input id="customerName" required placeholder="Customer’s legal name" /></div><div class="field"><label for="customerPhone">Mobile number *</label><input id="customerPhone" required placeholder="+1 555 000 0000" /></div><div class="field"><label for="customerEmail">Email address</label><input id="customerEmail" type="email" placeholder="name@example.com" /></div><div class="field field--wide"><label for="customerAddress">Installation address *</label><input id="customerAddress" required placeholder="Street, area, city, postal code" /></div></div><div class="form-section"><span>02</span><div><h3>Connection & plan</h3><p>Choose the customer’s product and plan.</p></div></div><div class="form-grid form-grid--three"><div class="field"><label for="orderType">Connection type *</label><select id="orderType"><option>Broadband</option><option>Dial-Up</option><option>Landline</option></select></div><div class="field"><label for="orderPlan">Plan selection *</label><select id="orderPlan"><option>Unlimited 64 Kbps · $225/mo</option><option>Essential 56 Kbps · $1.50/hr</option><option>Business Standard · $84.20/mo</option></select></div><div class="field"><label for="preferredDate">Preferred date</label><input id="preferredDate" type="date" /></div></div><div class="form-actions"><span>Sent to technical feasibility immediately.</span><button class="button button--primary">Create order →</button></div></form>`;
  if (view === "tracking") return lookupView("Order desk", "Track an order", "Enter the customer’s 11-character alphanumeric Order ID.", "trackingForm", "trackingId", "Order ID", "D0000000001", "trackingError", "trackingResult", orderResult(data.orders[0]));
  if (view === "connections") return lookupView("Customer account", "Connection details", "Use a 16-digit Account ID to retrieve live service and plan information.", "connectionLookupForm", "connectionAccount", "Account ID", "4851029384756102", "connectionLookupError", "connectionLookupResult");
  return lookupView("Cash desk", "Payment records", "Look up billing and payment details using a 16-digit Account ID.", "retailPaymentForm", "retailPaymentAccount", "Account ID", "4851029384756102", "retailPaymentError", "retailPaymentResult");
}
function lookupView(kicker, title, copy, form, input, label, placeholder, error, result, content = "") { return `${heading(kicker, title, copy)}<section class="surface lookup-panel"><form class="lookup-row" id="${form}"><div class="field"><label for="${input}">${label}</label><input id="${input}" class="mono-input" maxlength="${label === "Order ID" ? 11 : 16}" inputmode="${label === "Order ID" ? "text" : "numeric"}" placeholder="${placeholder}" /></div><button class="button button--primary">Find ${label === "Order ID" ? "order" : "account"}</button></form><small class="field-error" id="${error}"></small><div id="${result}">${content}</div></section>`; }

function queueTable() { return table(["Order", "Customer", "Service", "Status", "Update status"], data.orders.map(o => `<tr><td><b>${o.id}</b><small>${o.account}</small></td><td>${o.customer}</td><td>${o.type}</td><td>${chip(o.status)}</td><td><select class="table-select" data-order-status="${o.id}">${["Awaiting feasibility", "Feasible", "Not Feasible", "Connection Provided"].map(s => `<option ${s === o.status ? "selected" : ""}>${s}</option>`).join("")}</select></td></tr>`)); }
function equipmentTable() { return table(["Serial number", "Product", "Account ID", "Assigned", "State"], data.equipment.map(e => `<tr><td><b class="mono">${e.serial}</b></td><td>${e.type}</td><td class="mono">${e.account}</td><td>${e.assigned}</td><td>${chip("Assigned")}</td></tr>`)); }
function technicalView(view) {
  if (view === "overview") return `${heading("Field operations", "Technical command board", "Prioritize feasibility decisions and keep every active connection accounted for.", `<button class="button button--primary" data-view-link="queue">Open queue →</button>`)}<div class="metric-grid">${metric("Pending review", "23", "6 high priority", "metric--signal")}${metric("Feasible today", "18", "82% approval rate")}${metric("Connections installed", "14", "4 teams in field")}${metric("Equipment assigned", "27", "Zero serial conflicts")}</div>${activity()}`;
  if (view === "queue") return `${heading("Installation pipeline", "Order feasibility queue", "Review service availability and advance each order through installation.")}<section class="surface table-panel">${section("Pending orders", "Live queue")}<div id="queueTable">${queueTable()}</div></section>`;
  if (view === "connection-manager") return lookupView("Network control", "Connection manager", "Find an account and apply the correct service state.", "techConnectionForm", "techAccount", "Account ID", "4851029384756102", "techConnectionError", "techConnectionResult");
  return `${heading("Asset chain", "Equipment tracker", "Log each modem or router against the connection where it is installed.", `<button class="button button--primary" id="showEquipmentForm">+ Assign equipment</button>`)}<form class="surface inline-entry" id="equipmentForm" hidden><div class="field"><label for="equipmentSerial">Serial number</label><input id="equipmentSerial" required placeholder="RTR-NX-00000" /></div><div class="field"><label for="equipmentType">Product</label><select id="equipmentType"><option>Router</option><option>Modem</option></select></div><div class="field"><label for="equipmentAccount">Account ID</label><input id="equipmentAccount" required maxlength="16" inputmode="numeric" placeholder="16 digits" /></div><button class="button button--primary">Assign</button></form><section class="surface table-panel">${section("Assignment ledger", `${data.equipment.length} units`)}<div id="equipmentTable">${equipmentTable()}</div></section>`;
}

function billingView() { return `${heading("Invoice desk", "Generate a customer bill", "Enter an Account ID, confirm line items, then issue the total.", `<span class="period-tag">Billing period <b>September 2026</b></span>`)}<div class="billing-layout"><form class="surface form-panel" id="billingForm"><div class="field"><label for="billAccount">16-digit Account ID *</label><input id="billAccount" class="mono-input" maxlength="16" inputmode="numeric" value="4851029384756102" /></div><div class="line-items"><div class="line-items__head"><span>Billable item</span><span>Amount</span></div><label><span><b>Security deposit</b><small>Refundable connection deposit</small></span><input id="billDeposit" data-bill type="number" min="0" step="0.01" value="0.00" /></label><label><span><b>Monthly rental / hourly charges</b><small>Broadband Unlimited 64 Kbps</small></span><input id="billRental" data-bill type="number" min="0" step="0.01" value="225.00" /></label><div class="tax-row"><span><b>Service tax</b><small>Automated · 12.24%</small></span><strong id="billTax">$27.54</strong></div></div><button class="button button--primary button--wide">Calculate & generate bill</button><small class="field-error" id="billError"></small></form><aside class="invoice-card"><p class="eyebrow">Invoice preview</p><h3>Amount due</h3><div class="invoice-total"><small>Calculated total</small><strong id="billTotal">$252.54</strong><span>Due October 03, 2026</span></div><dl class="invoice-lines"><div><dt>Charges subtotal</dt><dd id="billSubtotal">$225.00</dd></div><div><dt>Service tax <span>12.24%</span></dt><dd id="billTaxSummary">$27.54</dd></div><div class="invoice-lines__total"><dt>Total due</dt><dd id="billTotalSmall">$252.54</dd></div></dl><div class="invoice-account"><small>Account</small><strong id="invoiceAccount">4851029384756102</strong></div></aside></div>`; }
function accountsView(view) {
  if (view === "overview") return `${heading("September close", "Revenue, clearly reconciled.", "Track billed value, collections, and outstanding account balances.", `<button class="button button--primary" data-view-link="billing">Generate bill →</button>`)}<div class="metric-grid">${metric("Billed this month", "$428.6k", "+8.2% month over month", "metric--signal")}${metric("Payments received", "$371.2k", "86.6% collected")}${metric("Outstanding", "$57.4k", "Across 312 accounts")}${metric("Service tax", "$46.7k", "12.24% automated")}</div>${activity()}`;
  if (view === "billing") return billingView();
  if (view === "payment-updates") return `${heading("Receivables", "Payment updates", "Post a received amount and keep the due balance accurate.")}<form class="surface form-panel" id="paymentUpdateForm"><div class="form-grid form-grid--three"><div class="field"><label for="paymentAccount">Account ID *</label><input id="paymentAccount" required maxlength="16" inputmode="numeric" placeholder="4851029384756102" /></div><div class="field money-field"><label for="amountPaid">Amount paid *</label><span>$</span><input id="amountPaid" required min="0" step="0.01" type="number" value="225.00" /></div><div class="field money-field"><label for="dueAmount">Due amount</label><span>$</span><input id="dueAmount" min="0" step="0.01" type="number" value="44.38" /></div></div><div class="form-actions"><span>Updates the account ledger after confirmation.</span><button class="button button--primary">Post payment →</button></div></form>`;
  return `${heading("Finance controls", "Charge settings", "Maintain base charges used by the billing calculator.")}<form class="surface form-panel" id="chargeSettingsForm"><div class="settings-list">${[["Security deposit", "One-time refundable connection deposit", "100.00"], ["Broadband monthly rental", "Unlimited 64 Kbps plan", "225.00"], ["Dial-Up hourly charge", "Essential 56 Kbps plan", "1.50"]].map(x => `<div><span><strong>${x[0]}</strong><small>${x[1]}</small></span><label>$ <input type="number" min="0" step="0.01" value="${x[2]}" /></label></div>`).join("")}<div><span><strong>Service tax</strong><small>Applied automatically to all billable items</small></span><label>% <input type="number" value="12.24" readonly /></label></div></div><div class="form-actions"><span>Tax is fixed at the required statutory rate.</span><button class="button button--primary">Save charge settings</button></div></form>`;
}

function safe(value) { return String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char]); }
function customerOrders() { return data.orders.filter(order => order.customer === data.customer.name); }
function customerOrderTable() {
  const orders = customerOrders();
  if (!orders.length) return `<div class="empty-state"><strong>No orders yet</strong><p>Your new service requests will appear here.</p><button class="button button--primary" data-view-link="customer-new-service">Explore services</button></div>`;
  return table(["Order", "Service", "Plan", "Status", "Details"], orders.map(order => `<tr><td><b>${order.id}</b><small>Account ${order.account.slice(-4)}</small></td><td>${order.type}</td><td>${order.plan}</td><td>${chip(order.status)}</td><td class="row-actions"><button data-customer-order="${order.id}">View progress</button></td></tr>`));
}
function customerBillTable() {
  return table(["Invoice", "Billing period", "Amount", "Due date", "Status"], data.customerBills.map(bill => `<tr><td><b>${bill.id}</b></td><td>${bill.period}</td><td class="number-cell">${money.format(bill.total)}</td><td>${bill.due}</td><td>${chip(bill.status)}</td></tr>`));
}
function customerView(view) {
  const customer = data.customer;
  const order = customerOrders()[0] || data.orders[0];
  const equipment = data.equipment.find(item => item.account === customer.account);
  const firstName = safe(customer.name.split(" ")[0]);

  if (view === "overview") return `${heading("Customer home", `Welcome back, ${firstName}.`, "Your service, requests, and payments are together in one simple account view.", `<button class="button button--primary" data-view-link="customer-new-service">Add a service</button>`)}<section class="customer-hero"><div><span class="customer-hero__status">${chip(data.connectionStatus[customer.account])}</span><p class="eyebrow">Current service</p><h2>${safe(order.type)} ${safe(order.plan)}</h2><p>Your connection at ${safe(customer.address)} is online and operating normally.</p><div class="customer-hero__actions"><button class="button button--light" data-view-link="customer-connection">View connection</button><button class="customer-text-link" data-view-link="customer-support">Get help</button></div></div><aside><small>Account ID</small><strong>${customer.account}</strong><span>Member since ${customer.memberSince}</span><div class="customer-signal" aria-label="Connection signal strong"><i></i><i></i><i></i><i></i></div></aside></section><div class="customer-metric-grid">${metric("Next bill", money.format(data.customerBills[0].total), `Due ${data.customerBills[0].due}`, "metric--signal")}${metric("Open orders", String(customerOrders().filter(item => !/provided/i.test(item.status)).length).padStart(2, "0"), "Track installation progress")}${metric("Service status", data.connectionStatus[customer.account], equipment ? `${equipment.type} ${equipment.serial}` : "Equipment pending")}</div><div class="customer-dashboard-grid"><section class="surface customer-activity">${section("Recent activity", "Account timeline")}<div class="feed"><p><i class="teal"></i><strong>September bill is ready</strong><small>${money.format(data.customerBills[0].total)} due ${data.customerBills[0].due}</small></p><p><i></i><strong>Router linked to your account</strong><small>${equipment ? equipment.serial : "Equipment assignment pending"}</small></p><p><i class="amber"></i><strong>Service request in review</strong><small>${order.id} is ${order.status.toLowerCase()}</small></p></div></section><aside class="surface customer-help-card"><p class="eyebrow">Need a hand?</p><h3>Support when you need it.</h3><p>Send a request with your account attached automatically.</p><button class="button button--secondary" data-view-link="customer-support">Contact support</button></aside></div>`;

  if (view === "customer-new-service") return `${heading("Service catalogue", "Add a new connection", "Choose a plan and tell us where you need it. Technical staff will confirm availability.")}<div class="customer-service-layout"><form class="surface form-panel" id="customerServiceForm"><div class="form-section"><span>01</span><div><h3>Select your service</h3><p>All prices shown before the fixed service tax.</p></div></div><fieldset class="customer-plan-grid"><legend class="sr-only">Available service plans</legend>${data.plans.map((plan, index) => `<label class="customer-plan-option"><input type="radio" name="customerPlan" value="${safe(`${plan.type}|${plan.plan}`)}" ${index === 0 ? "checked" : ""}/><span><small>${plan.type}</small><strong>${plan.plan}</strong><b>${money.format(plan.charge)}<em>${plan.billing === "Hourly" ? "/hr" : "/mo"}</em></b></span></label>`).join("")}</fieldset><div class="form-section"><span>02</span><div><h3>Installation details</h3><p>We will use these details for the feasibility check.</p></div></div><div class="form-grid"><div class="field field--wide"><label for="customerServiceAddress">Installation address *</label><input id="customerServiceAddress" required value="${safe(customer.address)}" /></div><div class="field"><label for="customerServiceDate">Preferred installation date *</label><input id="customerServiceDate" type="date" required /></div><div class="field"><label for="customerServiceContact">Contact method</label><select id="customerServiceContact"><option>Email</option><option>Phone</option><option>SMS</option></select></div></div><div class="form-actions"><span>No charge is made until feasibility is confirmed.</span><button class="button button--primary">Submit request</button></div><div id="customerServiceResult" aria-live="polite"></div></form><aside class="surface customer-expectation"><p class="eyebrow">What happens next</p><ol><li><span>1</span><div><strong>Request received</strong><small>Your order appears immediately.</small></div></li><li><span>2</span><div><strong>Coverage checked</strong><small>A technician confirms feasibility.</small></div></li><li><span>3</span><div><strong>Installation arranged</strong><small>We confirm a date with you.</small></div></li></ol></aside></div>`;

  if (view === "customer-orders") return `${heading("Requests", "My orders", "Review every service request and follow its installation progress.", `<button class="button button--primary" data-view-link="customer-new-service">New service request</button>`)}<section class="surface table-panel">${section("Order history", `${customerOrders().length} request${customerOrders().length === 1 ? "" : "s"}`)}<div id="customerOrderTable">${customerOrderTable()}</div><div id="customerOrderDetail">${order ? orderResult(order) : ""}</div></section>`;

  if (view === "customer-connection") return `${heading("Network", "My connection", "See the current service state, installed equipment, and account details.")}<div class="customer-connection-grid"><section class="surface customer-connection-card"><div class="customer-connection-card__top"><div><p class="eyebrow">Live connection</p><h3>${safe(order.type)} ${safe(order.plan)}</h3></div>${chip(data.connectionStatus[customer.account])}</div><div class="customer-connection-visual" aria-hidden="true"><span>NEXUS</span><i></i><b>ONLINE</b></div><dl><div><dt>Account ID</dt><dd class="mono">${customer.account}</dd></div><div><dt>Service address</dt><dd>${safe(customer.address)}</dd></div><div><dt>Equipment</dt><dd>${equipment ? `${equipment.type} ${equipment.serial}` : "Pending assignment"}</dd></div><div><dt>Last status check</dt><dd>Today, 09:42</dd></div></dl></section><aside class="surface customer-diagnostics"><p class="eyebrow">Quick checks</p><h3>Connection health</h3><div><span>Network status</span><strong class="positive-text">Operational</strong></div><div><span>Equipment</span><strong>Connected</strong></div><div><span>Service incidents</span><strong>None reported</strong></div><button class="button button--secondary button--wide" data-view-link="customer-support">Report a problem</button></aside></div>`;

  if (view === "customer-billing") return `${heading("Account balance", "Bills & payments", "Check current charges and review your recent payment history.", `<button class="button button--primary" id="customerPayNow">Pay ${money.format(data.customerBills[0].total)}</button>`)}<div class="customer-billing-summary"><article class="customer-balance-card"><p class="eyebrow">Current amount due</p><strong>${money.format(data.customerBills[0].total)}</strong><span>Payment due ${data.customerBills[0].due}</span><div><small>Monthly rental</small><b>$225.00</b></div><div><small>Service tax</small><b>$27.54</b></div></article><section class="surface customer-payment-note"><p class="eyebrow">Payment details</p><h3>Your account is up to date.</h3><p>The current invoice is not overdue. Your last payment of $225.00 was received on Aug 30, 2026.</p><button class="button button--secondary" id="customerDownloadBill">Download current bill</button></section></div><section class="surface table-panel">${section("Billing history", "Recent invoices")}<div id="customerBillTable">${customerBillTable()}</div></section>`;

  if (view === "customer-profile") return `${heading("Personal details", "My profile", "Keep your contact information current so service updates reach you.")}<form class="surface form-panel customer-profile-form" id="customerProfileForm"><div class="customer-profile-head"><span>${safe(customer.name.split(" ").map(part => part[0]).join("").slice(0, 2))}</span><div><strong>${safe(customer.name)}</strong><small>Customer since ${customer.memberSince}</small></div></div><div class="form-grid"><div class="field"><label for="profileName">Full name *</label><input id="profileName" required value="${safe(customer.name)}" /></div><div class="field"><label for="profileEmail">Email address *</label><input id="profileEmail" type="email" required value="${safe(customer.email)}" /></div><div class="field"><label for="profilePhone">Mobile number *</label><input id="profilePhone" required value="${safe(customer.phone)}" /></div><div class="field"><label for="profileContact">Preferred contact</label><select id="profileContact">${["Email", "Phone", "SMS"].map(item => `<option ${item === customer.contact ? "selected" : ""}>${item}</option>`).join("")}</select></div><div class="field field--wide"><label for="profileAddress">Service address</label><input id="profileAddress" value="${safe(customer.address)}" readonly /></div></div><div class="form-actions"><span>Account ID ${customer.account}</span><button class="button button--primary">Save profile</button></div></form>`;

  return `${heading("Help centre", "How can we help?", "Send a support request and your account details will be attached automatically.")}<div class="customer-support-layout"><form class="surface form-panel" id="customerSupportForm"><div class="field"><label for="supportTopic">What do you need help with? *</label><select id="supportTopic" required><option value="">Choose a topic</option><option>Connection problem</option><option>Billing question</option><option>Installation update</option><option>Account details</option><option>Other</option></select></div><div class="field"><label for="supportSubject">Subject *</label><input id="supportSubject" required maxlength="80" placeholder="A short summary" /></div><div class="field"><label for="supportMessage">Tell us more *</label><textarea id="supportMessage" required rows="6" placeholder="Include what happened and when it started"></textarea></div><div class="form-actions"><span>Replies will be sent by ${customer.contact.toLowerCase()}.</span><button class="button button--primary">Send support request</button></div><div id="customerSupportResult" aria-live="polite"></div></form><aside class="surface customer-contact-card"><p class="eyebrow">Direct contact</p><h3>Talk to the service team.</h3><dl><div><dt>Customer care</dt><dd>1 800 NEXUS 01</dd></div><div><dt>Hours</dt><dd>Mon to Sat, 08:00 to 20:00</dd></div><div><dt>Emergency faults</dt><dd>Available 24 hours</dd></div></dl><p>Your account ID</p><strong class="mono">${customer.account}</strong></aside></div>`;
}

function renderRole(role, view = "overview") { activeRole = roles[role] ? role : "admin"; const r = roles[activeRole]; $("#roleName").textContent = r.name; $("#roleCode").textContent = r.code; $("#viewContext").textContent = r.context; $("#quickRole").value = activeRole; $("#primaryNav").innerHTML = `<p class="nav__label">Workspace</p>${r.nav.map(([id, label], i) => `<a class="nav__item" href="#${id}" data-view-link="${id}"><span>${icons[id]}</span><em>${label}</em><small>0${i + 1}</small></a>`).join("")}`; showView(view); }
function showView(view) { const r = roles[activeRole], target = r.nav.find(x => x[0] === view) || r.nav[0]; currentView = target[0]; $("#viewTitle").textContent = target[1]; $$(".nav__item").forEach(a => { const on = a.dataset.viewLink === currentView; a.classList.toggle("is-active", on); on ? a.setAttribute("aria-current", "page") : a.removeAttribute("aria-current"); }); const render = activeRole === "customer" ? customerView : activeRole === "admin" ? adminView : activeRole === "retail" ? retailView : activeRole === "technical" ? technicalView : accountsView; $("#roleContent").innerHTML = `<section class="view is-active">${render(currentView)}</section>`; history.replaceState(null, "", `#${currentView}`); closeSidebar(); bindView(); window.scrollTo({ top: 0, behavior: "smooth" }); }

document.addEventListener("click", e => {
  const nav = e.target.closest("[data-view-link]"); if (nav && !$("#appView").hidden) { e.preventDefault(); showView(nav.dataset.viewLink); }
  const add = e.target.closest("[data-add]"); if (add) openModal(add.dataset.add);
  const ee = e.target.closest("[data-edit-employee]"); if (ee) openModal("employee", data.employees.find(x => x.id === ee.dataset.editEmployee));
  const ev = e.target.closest("[data-edit-vendor]"); if (ev) openModal("vendor", data.vendors.find(x => x.id === ev.dataset.editVendor));
  const de = e.target.closest("[data-delete-employee]"); if (de) remove("employee", de.dataset.deleteEmployee);
  const dv = e.target.closest("[data-delete-vendor]"); if (dv) remove("vendor", dv.dataset.deleteVendor);
  const customerOrder = e.target.closest("[data-customer-order]"); if (customerOrder) { const order = data.orders.find(item => item.id === customerOrder.dataset.customerOrder && item.customer === data.customer.name); if (order && $("#customerOrderDetail")) { $("#customerOrderDetail").innerHTML = orderResult(order); $("#customerOrderDetail").scrollIntoView({ behavior: "smooth", block: "nearest" }); } }
  if (e.target.closest("[data-close-modal]")) closeModal();
});

function bindView() {
  $("#employeeSearch")?.addEventListener("input", e => { const q = e.target.value.toLowerCase(); $("#employeeTable").innerHTML = employeeTable(data.employees.filter(x => Object.values(x).some(v => v.toLowerCase().includes(q)))); });
  $("#orderForm")?.addEventListener("submit", createOrder);
  $("#trackingForm")?.addEventListener("submit", e => findOrder(e, "trackingId", "trackingError", "trackingResult"));
  $("#connectionLookupForm")?.addEventListener("submit", e => findAccount(e, "connectionAccount", "connectionLookupError", "connectionLookupResult", o => accountResult(o)));
  $("#retailPaymentForm")?.addEventListener("submit", e => findAccount(e, "retailPaymentAccount", "retailPaymentError", "retailPaymentResult", o => accountResult(o, true)));
  $$("[data-order-status]").forEach(s => s.addEventListener("change", () => { const o = data.orders.find(x => x.id === s.dataset.orderStatus); o.status = s.value; $("#queueTable").innerHTML = queueTable(); bindView(); showToast(`${o.id} updated to ${o.status}.`); }));
  $("#techConnectionForm")?.addEventListener("submit", loadConnection);
  $("#showEquipmentForm")?.addEventListener("click", () => { $("#equipmentForm").hidden = false; $("#equipmentSerial").focus(); });
  $("#equipmentForm")?.addEventListener("submit", addEquipment);
  $$("[data-bill]").forEach(x => x.addEventListener("input", calculateBill)); $("#billingForm")?.addEventListener("submit", generateBill);
  $("#paymentUpdateForm")?.addEventListener("submit", simpleSubmit("Payment posted and account balance updated."));
  $("#chargeSettingsForm")?.addEventListener("submit", simpleSubmit("Charge settings saved."));
  $("#customerServiceForm")?.addEventListener("submit", createCustomerService);
  $("#customerProfileForm")?.addEventListener("submit", saveCustomerProfile);
  $("#customerSupportForm")?.addEventListener("submit", sendCustomerSupport);
  $("#customerPayNow")?.addEventListener("click", () => showToast("Secure payment handoff is ready for backend integration."));
  $("#customerDownloadBill")?.addEventListener("click", () => showToast(`${data.customerBills[0].id} is ready to download.`));
  if ($("#customerServiceDate")) $("#customerServiceDate").min = new Date().toISOString().slice(0, 10);
  $("#addPlan")?.addEventListener("click", () => showToast("Plan editor is ready for backend integration.")); calculateBill();
}

function createOrder(e) { e.preventDefault(); if (!e.currentTarget.reportValidity()) return; const id = `D${String(data.orders.length + 1).padStart(10, "0")}`, account = String(Math.floor(1000000000000000 + Math.random() * 8999999999999999)); data.orders.unshift({ id, account, customer: $("#customerName").value.trim(), type: $("#orderType").value, plan: $("#orderPlan").value.split(" · ")[0], status: "Awaiting feasibility", due: 0 }); showToast(`Order ${id} created and sent for feasibility.`); e.currentTarget.reset(); }
function createCustomerService(e) {
  e.preventDefault();
  if (!e.currentTarget.reportValidity()) return;
  const selection = $("input[name=customerPlan]:checked").value.split("|");
  const id = `D${String(data.orders.length + 1).padStart(10, "0")}`;
  const plan = data.plans.find(item => item.type === selection[0] && item.plan === selection[1]);
  const order = { id, account: data.customer.account, customer: data.customer.name, type: selection[0], plan: selection[1], status: "Awaiting feasibility", due: plan?.charge || 0 };
  data.orders.unshift(order);
  $("#customerServiceResult").innerHTML = `<div class="customer-success"><span>OK</span><div><strong>Request ${id} received</strong><p>Your ${safe(order.type)} request is now waiting for a coverage check. You can follow it in My Orders.</p></div><button class="customer-text-link" type="button" data-view-link="customer-orders">Track order</button></div>`;
  showToast(`Service request ${id} created.`);
}
function saveCustomerProfile(e) {
  e.preventDefault();
  if (!e.currentTarget.reportValidity()) return;
  const previousName = data.customer.name;
  Object.assign(data.customer, { name: $("#profileName").value.trim(), email: $("#profileEmail").value.trim(), phone: $("#profilePhone").value.trim(), contact: $("#profileContact").value });
  data.orders.filter(order => order.customer === previousName).forEach(order => { order.customer = data.customer.name; });
  $("#welcomeText").textContent = data.customer.name;
  $("#userInitials").textContent = data.customer.name.split(/\s+/).map(part => part[0]).join("").slice(0, 2).toUpperCase();
  showToast("Profile details saved.");
}
function sendCustomerSupport(e) {
  e.preventDefault();
  if (!e.currentTarget.reportValidity()) return;
  const reference = `SR-${Date.now().toString().slice(-6)}`;
  $("#customerSupportResult").innerHTML = `<div class="customer-success"><span>OK</span><div><strong>Support request ${reference} sent</strong><p>Customer care will reply by ${safe(data.customer.contact.toLowerCase())}.</p></div></div>`;
  e.currentTarget.reset();
  showToast(`Support request ${reference} sent.`);
}
function findOrder(e, input, error, result) { e.preventDefault(); const value = $(`#${input}`).value.trim().toUpperCase(), found = data.orders.find(o => o.id === value); $(`#${error}`).textContent = /^[A-Z0-9]{11}$/.test(value) ? (found ? "" : "No order matches that ID.") : "Enter exactly 11 letters or numbers."; $(`#${result}`).innerHTML = found ? orderResult(found) : ""; }
function findAccount(e, input, error, result, render) { e.preventDefault(); const value = $(`#${input}`).value.trim(), found = data.orders.find(o => o.account === value); $(`#${error}`).textContent = /^\d{16}$/.test(value) ? (found ? "" : "No account matches that ID.") : "Account IDs must contain exactly 16 digits."; $(`#${result}`).innerHTML = found ? render(found) : ""; return found; }
function loadConnection(e) { const found = findAccount(e, "techAccount", "techConnectionError", "techConnectionResult", o => `<article class="result-card"><div class="result-card__top"><div><small>Connection owner</small><strong>${o.customer}</strong></div>${chip(data.connectionStatus[o.account])}</div><div class="connection-control"><p><small>Account ID</small><strong class="mono">${o.account}</strong></p><fieldset><legend>Connection status</legend>${["Active", "Temporarily Inactive", "Permanently Inactive"].map(s => `<label><input type="radio" name="connectionState" value="${s}" ${data.connectionStatus[o.account] === s ? "checked" : ""}/><span>${s}</span></label>`).join("")}</fieldset><button class="button button--primary" type="button" id="saveConnectionState" data-account="${o.account}">Apply status</button></div></article>`); if (found) $("#saveConnectionState").addEventListener("click", ev => { const a = ev.currentTarget.dataset.account; data.connectionStatus[a] = $("input[name=connectionState]:checked").value; showToast(`Connection set to ${data.connectionStatus[a]}.`); }); }
function addEquipment(e) { e.preventDefault(); const a = $("#equipmentAccount").value.trim(); if (!/^\d{16}$/.test(a)) return showToast("Enter a valid 16-digit Account ID."); data.equipment.unshift({ serial: $("#equipmentSerial").value.trim().toUpperCase(), type: $("#equipmentType").value, account: a, assigned: new Date().toISOString().slice(0, 10) }); $("#equipmentTable").innerHTML = equipmentTable(); e.currentTarget.reset(); e.currentTarget.hidden = true; showToast("Equipment assigned to connection."); }

// Form submission recalculates subtotal + fixed 12.24% service tax, validates the
// 16-digit account, updates the invoice preview, then creates a demo reference.
function calculateBill() { if (!$("#billRental")) return; const subtotal = Math.max(0, +$("#billDeposit").value || 0) + Math.max(0, +$("#billRental").value || 0), tax = subtotal * .1224; lastBillTotal = subtotal + tax; [["billSubtotal", subtotal], ["billTax", tax], ["billTaxSummary", tax], ["billTotal", lastBillTotal], ["billTotalSmall", lastBillTotal]].forEach(([id, value]) => $(`#${id}`).textContent = money.format(value)); }
function generateBill(e) { e.preventDefault(); const a = $("#billAccount").value.trim(); if (!/^\d{16}$/.test(a)) return $("#billError").textContent = "Enter a valid 16-digit Account ID."; $("#billError").textContent = ""; $("#invoiceAccount").textContent = a; calculateBill(); showToast(`Bill NX-${Date.now().toString().slice(-6)} generated for ${money.format(lastBillTotal)}.`); }
function simpleSubmit(message) { return e => { e.preventDefault(); if (e.currentTarget.reportValidity()) showToast(message); }; }

function openModal(type, record = null) { modalState = { type, id: record?.id || null }; const employee = type === "employee"; $("#modalEyebrow").textContent = employee ? "People operations" : "Supply partners"; $("#modalTitle").textContent = `${record ? "Edit" : "Add"} ${type}`; $("#modalSave").textContent = record ? "Save changes" : `Add ${type}`; $("#modalFields").innerHTML = employee ? `<div class="field"><label for="recordName">Full name</label><input id="recordName" required value="${record?.name || ""}" /></div><div class="form-grid"><div class="field"><label for="recordRole">Role</label><select id="recordRole"><option>Retail Employee</option><option>Technical Staff</option><option>Accounts</option><option>Manager</option></select></div><div class="field"><label for="recordOutlet">Assignment</label><input id="recordOutlet" required value="${record?.outlet || ""}" /></div></div><div class="field"><label for="recordStatus">Status</label><select id="recordStatus"><option>Active</option><option>On leave</option><option>Inactive</option></select></div>` : `<div class="field"><label for="recordName">Vendor name</label><input id="recordName" required value="${record?.name || ""}" /></div><div class="form-grid"><div class="field"><label for="recordContact">Contact person</label><input id="recordContact" required value="${record?.contact || ""}" /></div><div class="field"><label for="recordCategory">Category</label><input id="recordCategory" required value="${record?.category || ""}" /></div></div><div class="field"><label for="recordStatus">Status</label><select id="recordStatus"><option>Approved</option><option>Review</option><option>Suspended</option></select></div>`; if (record) { if (employee) $("#recordRole").value = record.role; $("#recordStatus").value = record.status; } $("#recordModal").hidden = false; document.body.classList.add("modal-open"); $("#recordName").focus(); }
function closeModal() { $("#recordModal").hidden = true; document.body.classList.remove("modal-open"); modalState = null; }
$("#recordForm").addEventListener("submit", e => { e.preventDefault(); if (!e.currentTarget.reportValidity()) return; const employee = modalState.type === "employee", list = employee ? data.employees : data.vendors, current = list.find(x => x.id === modalState.id), values = employee ? { name: $("#recordName").value.trim(), role: $("#recordRole").value, outlet: $("#recordOutlet").value.trim(), status: $("#recordStatus").value } : { name: $("#recordName").value.trim(), contact: $("#recordContact").value.trim(), category: $("#recordCategory").value.trim(), status: $("#recordStatus").value }; current ? Object.assign(current, values) : list.unshift({ id: `${employee ? "EMP" : "VND"}-${String(list.length + 21).padStart(2, "0")}`, ...values }); const noun = modalState.type; closeModal(); showView(currentView); showToast(`${noun[0].toUpperCase() + noun.slice(1)} ${current ? "updated" : "added"}.`); });
function remove(type, id) { const list = type === "employee" ? data.employees : data.vendors, record = list.find(x => x.id === id); if (!record || !confirm(`Delete ${record.name}?`)) return; list.splice(list.indexOf(record), 1); showView(currentView); showToast(`${record.name} deleted.`); }

function fieldError(id, message) { const f = $(`#${id}`); f.classList.toggle("is-invalid", !!message); f.setAttribute("aria-invalid", String(!!message)); $(`#${id}Error`).textContent = message; }
$("#loginForm").addEventListener("submit", e => { e.preventDefault(); const user = $("#username").value.trim(), pass = $("#password").value, role = $("#role").value; fieldError("username", user ? "" : "Enter your username."); fieldError("password", pass ? "" : "Enter your password."); fieldError("role", role ? "" : "Choose a workspace."); if (!user || !pass || !role) return; $("#userInitials").textContent = user.split(/[.\s_-]+/).map(p => p[0]).join("").slice(0, 2).toUpperCase(); $("#welcomeText").textContent = user.split(/[._-]/).map(p => p[0].toUpperCase() + p.slice(1)).join(" "); $("#loginView").hidden = true; $("#appView").hidden = false; renderRole(role); showToast(`${roles[role].name} workspace ready.`); });
$$("#loginForm input, #loginForm select").forEach(f => f.addEventListener("input", () => fieldError(f.id, "")));
$("#passwordToggle").addEventListener("click", () => { const f = $("#password"); f.type = f.type === "password" ? "text" : "password"; $("#passwordToggle").textContent = f.type === "password" ? "Show" : "Hide"; });
$("#quickRole").addEventListener("change", e => { renderRole(e.target.value); showToast(`Switched to ${roles[e.target.value].name}.`); });
$("#logoutButton").addEventListener("click", () => { $("#appView").hidden = true; $("#loginView").hidden = false; $("#loginForm").reset(); $("#username").focus(); });
function closeSidebar() { $("#sidebar").classList.remove("is-open"); $("#sidebarScrim").classList.remove("is-visible"); }
$("#menuButton").addEventListener("click", () => { $("#sidebar").classList.add("is-open"); $("#sidebarScrim").classList.add("is-visible"); }); $("#sidebarClose").addEventListener("click", closeSidebar); $("#sidebarScrim").addEventListener("click", closeSidebar); document.addEventListener("keydown", e => { if (e.key === "Escape") { closeSidebar(); if (!$("#recordModal").hidden) closeModal(); } });
$("#currentDate").textContent = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date());
